(define (fast-exp b n)
  (define (util b n a)
    (cond ((= n 0) a)
          ((even? n) (util (* b b) (/ n 2) a))
          (else (util (* b b) (/ (- n 1) 2) (* a b)))
          )
    )
  (util b n 1)
  )
