(define (fast-mul b n)
  (define (double n) (+ n n))
  (define (halve n) (/ n 2))
  (define (util b n a)
    (cond ((= n 0) a)
          ((even? n) (util (double b) (halve n) a))
          (else (util (double b) (halve (- n 1)) (+ a b)))
          )
    )
  (util b n 0)
  )
